apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - k8s/*
