apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: erashishchawla/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: erashishchawla/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
    - image: erashishchawla/ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: erashishchawla/ticketing-orders
      context: orders
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: erashishchawla/ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
manifests:
  rawYaml:
    - k8s/*
