apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth-mongo
  template:
    metadata:
      labels:
        component: auth-mongo
    spec:
      containers:
        - name: auth-mongo
          image: mongo
          ports:
            - containerPort: 27017
