apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-cluster-ip-service
spec:
  selector:
    component: auth-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
