apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: ticketing/auth:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: auth-mongo-cluster-ip-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: auth
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-jwt-secret
                  key: JWT_KEY
