# This file is used to create a deployment for the tickets service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orders
  template:
    metadata:
      labels:
        component: orders
    spec:
      containers:
        - name: orders
          image: erashishchawla/ticketing-orders:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: orders-mongo-srv
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: orders
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_HOST
              value: nats-srv
            - name: NATS_PORT
              value: "4222"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-jwt-secret
                  key: JWT_KEY
---
# This file is used to create a Cluster IP service for the tickets service

apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    component: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000

---
# This file is used to create a deployment for the tickets mongo service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orders-mongo
  template:
    metadata:
      labels:
        component: orders-mongo
    spec:
      containers:
        - name: orders-mongo
          image: mongo
          ports:
            - containerPort: 27017

---
# This file is used to create a Cluster IP service for the tickets mongo service
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    component: orders-mongo
  ports:
    - name: orders-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
